AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation template for creating Secrets Manager, IAM groups and users, Parameter Store, and Event bridge rules.

Resources:
  #Secret Manager for One-time password
  OneTimePasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: One-time password for IAM users
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: otp
        PasswordLength: 16
        ExcludeCharacters: '"\'\\/@'

  # S3 Read-only Group
  S3ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: S3ReadOnlyGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  # EC2 Read-only Group
  EC2ReadOnlyGroup:
      Type: AWS::IAM::Group
      Properties:
      GroupName: EC2ReadOnlyGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

  # IAM user: S3-User
  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: s3-user
      Groups:
        - !Ref S3ReadOnlyGroup
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${OneTimePasswordSecret}:SecretString:otp}}'
        PasswordResetRequired: true

  # IAM user:  EC2-User
    EC2User:
        Type: AWS::IAM::User
        Properties:
        UserName: ec2-user
        Groups:
            - !Ref EC2ReadOnlyGroup
        LoginProfile:
          Password: !Sub '{{resolve:secretsmanager:${OneTimePasswordSecret}:SecretString:otp}}'
          PasswordResetRequired: true